### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SivanMehta** [SivanMehta/driver#2]
Basic platformer:

- [ ] Should have stars and diamonds that increase score by 10 and 50 respectively
- [ ] Should have enemies
- [ ] Should have health
- [ ] Should be able to recover health with healthpack
